Repository LINKLION-KNU/NEWSPACT-SERVER, pull requests merged in 2024-08, with the labels that each got.

#54 🔥 remove dto sid, articleUrl
  src/main/java/org/likelion/newsfactbackend/domain/news/dto/response/ResponseNewsDto.java
Labels: refactoring

#58 :bug: Fix profile url bug
  src/main/java/org/likelion/newsfactbackend/user/domain/User.java
Labels: bug

#62 🐛 fix remove html tag
  src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java
Labels: bug, refactoring

#63 🐛 update multiple images
  src/main/java/org/likelion/newsfactbackend/domain/news/dto/response/ResponseNewsDto.java
  src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java
Labels: bug, refactoring

#66 🐛 Fix search bug
  src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java
Labels: bug

#75 :art: Add comment
  src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java
Labels: cleanup, docs
