Repository LINKLION-KNU/NEWSPACT-SERVER, pull requests merged in 2024-07, with the labels that each got.

#29 ✨ Add google oauth function
  .gitignore
  .idea/.gitignore
  src/main/java/org/likelion/newsfactbackend/domain/auth/controller/AuthController.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dao/AuthDAO.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dao/NicknameDAO.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/AuthDAOImpl.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/NicknameDAOImpl.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dto/request/RequestSaveUserDto.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dto/request/RequestSignInDto.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/service/AuthService.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/org/likelion/newsfactbackend/domain/scraps/domain/Scraps.java
  src/main/java/org/likelion/newsfactbackend/global/security/JwtTokenProvider.java
  src/main/java/org/likelion/newsfactbackend/user/domain/User.java
  src/main/java/org/likelion/newsfactbackend/user/repository/UserRepository.java
Labels: good first issue

#34 ✨ Add news controller, exception
  src/main/java/org/likelion/newsfactbackend/domain/news/controller/NewsController.java
  src/main/java/org/likelion/newsfactbackend/domain/news/dto/Keyword.java
  src/main/java/org/likelion/newsfactbackend/domain/news/dto/request/PageRequestNewsDto.java
  src/main/java/org/likelion/newsfactbackend/domain/news/dto/request/RequestNewsDto.java
  src/main/java/org/likelion/newsfactbackend/domain/news/dto/response/ResponseNewsDto.java
  src/main/java/org/likelion/newsfactbackend/domain/news/exception/ControllerExceptionHandler.java
  src/main/java/org/likelion/newsfactbackend/domain/news/exception/ErrorCode.java
  src/main/java/org/likelion/newsfactbackend/domain/news/exception/NewsException.java
  src/main/java/org/likelion/newsfactbackend/domain/news/exception/ResponseErrorDto.java
  src/main/java/org/likelion/newsfactbackend/domain/news/service/NewsService.java
  src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java
  src/main/java/org/likelion/newsfactbackend/domain/scraps/controller/ScrapsController.java
  src/main/java/org/likelion/newsfactbackend/global/domain/enums/LoginType.java
  src/test/java/org/likelion/newsfactbackend/domain/news/dto/response/ResponseNewsDtoTest.java
Labels: good first issue

#37 :bug: Fix jpa custom method
  src/main/java/org/likelion/newsfactbackend/NewsFactBackendApplication.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/AuthDAOImpl.java
  src/main/java/org/likelion/newsfactbackend/global/security/JwtTokenProvider.java
  src/main/java/org/likelion/newsfactbackend/global/security/SecurityConfiguration.java
  src/main/java/org/likelion/newsfactbackend/user/repository/UserRepository.java
  src/main/java/org/likelion/newsfactbackend/user/service/impl/UserDetailsServiceImpl.java
Labels: bug

#41 ✨ Add logout function
  pom.xml
  src/main/java/org/likelion/newsfactbackend/domain/auth/controller/AuthController.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dao/AuthDAO.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/AuthDAOImpl.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dto/response/ResponseAuthDto.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/service/AuthService.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/org/likelion/newsfactbackend/global/config/RedisConfig.java
  src/main/java/org/likelion/newsfactbackend/global/domain/enums/ResultCode.java
  src/main/java/org/likelion/newsfactbackend/global/security/JwtAuthenticationFilter.java
  src/main/java/org/likelion/newsfactbackend/global/security/JwtTokenProvider.java
  src/main/java/org/likelion/newsfactbackend/global/security/SecurityConfiguration.java
  src/main/java/org/likelion/newsfactbackend/user/domain/User.java
Labels: feat, cleanup

#45 :sparkles: Add scraps function
  src/main/java/org/likelion/newsfactbackend/domain/scraps/controller/ScrapsController.java
  src/main/java/org/likelion/newsfactbackend/domain/scraps/dao/ScrapsDAO.java
  src/main/java/org/likelion/newsfactbackend/domain/scraps/dao/impl/ScrapsDAOImpl.java
  src/main/java/org/likelion/newsfactbackend/domain/scraps/domain/Scraps.java
  src/main/java/org/likelion/newsfactbackend/domain/scraps/dto/request/RequestSaveScrapsDto.java
  src/main/java/org/likelion/newsfactbackend/domain/scraps/dto/response/ResponseScrapsNewsDto.java
  src/main/java/org/likelion/newsfactbackend/domain/scraps/repository/ScrapsRepository.java
  src/main/java/org/likelion/newsfactbackend/domain/scraps/service/ScrapsService.java
  src/main/java/org/likelion/newsfactbackend/domain/scraps/service/impl/ScrapsServiceImpl.java
  src/main/java/org/likelion/newsfactbackend/global/domain/enums/ResultCode.java
  src/main/java/org/likelion/newsfactbackend/user/domain/User.java
Labels: feat

#44 ✨ create Recommend News
  pom.xml
  src/main/java/org/likelion/newsfactbackend/domain/news/controller/NewsController.java
  src/main/java/org/likelion/newsfactbackend/domain/news/dto/RecommendNewsDto.java
  src/main/java/org/likelion/newsfactbackend/domain/news/service/NewsService.java
  src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java
Labels: feat, cleanup

#50 :bug: Fix redis config
  src/main/java/org/likelion/newsfactbackend/global/config/RedisConfig.java
Labels: bug

#48 :art: Change variable name
  src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/AuthDAOImpl.java
  src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/NicknameDAOImpl.java
  src/main/java/org/likelion/newsfactbackend/global/domain/enums/ResultCode.java
  src/main/java/org/likelion/newsfactbackend/global/security/JwtAuthenticationFilter.java
  src/main/java/org/likelion/newsfactbackend/global/security/SecurityConfiguration.java
Labels: cleanup

#52 ✨ create news category
  src/main/java/org/likelion/newsfactbackend/domain/news/controller/NewsController.java
  src/main/java/org/likelion/newsfactbackend/domain/news/dto/response/ResponseNewsDto.java
  src/main/java/org/likelion/newsfactbackend/domain/news/service/NewsService.java
  src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java
Labels: feat
